version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: master_user
      POSTGRES_PASSWORD: master_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - MASTER_DB_URL=postgresql://master_user:master_pass@db/master
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
